PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?subject ?label ?comment
	WHERE 
	{ 
		?subject a owl:Class 
		OPTIONAL { ?subject a rdfs:Class }
		OPTIONAL { ?subject rdfs:label ?label }
		OPTIONAL { ?subject rdfs:comment ?comment}
	}
	