
SELECT DISTINCT *
	WHERE 
	{	@predicateUri rdfs:range ?super .
		?item (rdfs:subClassOf|(owl:equivalentClass|^owl:equivalentClass))* ?super.
		?item rdfs:label ?label .
		OPTIONAL { ?item rdfs:comment ?comment}
	}