SELECT DISTINCT *
	WHERE 
	{ 
		@classTriplets 
		?subject a ?type .
		?subject rdfs:domain ?propertyOf
		OPTIONAL { ?subject a rdfs:Class }
		OPTIONAL { ?subject rdfs:label ?label }
		OPTIONAL { ?subject rdfs:comment ?comment}
	}
